### ISSUE TITLE
Can't run without docker

### ISSUE THREAD

**Issue by NuriYuri** [kwerle/ide-ruby#15]
You may think I'm stupid but... Docker requires Windows Entreprise to run which I don't have since I'm not a regular user thus the docker thing refuse to install cause it requires Hyper-V :v 

![image](https://user-images.githubusercontent.com/7335788/42656920-080b7ec8-8621-11e8-9efa-c8e45ee4dba6.png)

Consider a way to launch the thing without Docker ? I'd like to try the thing ^^'

**Comment by kwerle** [comment]
There are many reasons I use docker.  One of them is that I refuse to try to run ruby on Windows.

If you can get the ruby_language_server to run on your system (which is where practically all of the functionality is) and want *a little* help connecting it to a modified ide-ruby, I may be able to lend a hand.  

Otherwise I'm afraid you're out of luck.

Oh, and the ruby_language_server is just about to get updated such that it will depend a lot more on  it running within docker.

Part of the huge win with docker is that I will be able to install all the gems for the project you're editing inside the container and access all the functionality of those and the documentation and provide that information without polluting  the host system.  It is such a spectacularly good match for this kind of stuff.

You might consider installing docker-toolbox.  This will be a way less fancy experience, but I'm afraid it's about all you'll be able to get - without upgrading Windows or booting linux...
